server:
  port: 8091

#Admin configuration
info:
  name: @app.id@
  description: @app.id@
  version: @pom.version@
  stage: local

spring:
  application:
    id: @app.id@
    name: @app.id@
  boot:
    admin:
      client:
        url: ${boot.admin.client.url}
        username: ${boot.admin.client.username}
        password: ${boot.admin.client.password}
        instance:
          metadata:
            enable-oauth2: true

security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1tkDD7SrIgQRadKBYJje
          9rxadzHOvpThUwW/zJV6VG2XsDXFwltYcbHHzOwanBWvecsHaAomdS+VzmA7bjjR
          EsOa8G6N2uBhRHxPn4vRJldbUkl/NyOfxOJLJGZ5bruCMwIjBTjNM2mmowj9wD3p
          0VLrJs65U/7BIY4mwZDaWz0IYBN3JBvk2EFeBONUXkp71CdZPDutnTnwkO/dLK6W
          UQ8aTQFzQtYNZxxRV/G/5nYN/Bo2aAsgI4G2MRCfKzVdjVK3eEgsvHDWO0YIHhoF
          kpOCZjFYt0Ve4Wzz0XYnZQgdv9qkhhy0GQUnmuttHXrRCS0xBHRx4uy8kneE3AQD
          zQIDAQAB
          -----END PUBLIC KEY-----
swagger:
  paths: /api.*
  api.info:
    title: @app.id@
    description: @pom.description@ Documentation
    contact: @swagger.project.contact@
    version: @pom.version@
    license: license
    licenseUrl: http://easyms.fr/LICENSE-0.0.1.html
  security:
    oauth2:
      client:
        clientId: swagger
        clientSecret: secret
  securityDefinitions:
    oauthSecurity:
      type: oauth2
      tokenUrl: http://localhost:2000/oauth/token
      flow: password
      scopes:

easyms:
  logging:
    logstash: # Forward logs to logstash over a socket, used by LoggingConfig
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512

management.endpoints.web.exposure.include: "*"

